### ISSUE TITLE
Eclipse marketplace points to the 410 repo which does not work with latest eclipse 2022-12

### ISSUE THREAD

**Issue by marioja** [eclipse/ajdt#32]
It is not possible without being in the know to pick the 426 plugin repo from https://download.eclipse.org/tools/ajdt/426/dev/update/.

**Comment by kriegaex** [comment]
Sorry, that entry was not maintained for year. Until today, I did not even have access rights to manage the entry. Now I do, and I updated it. All AJDT update sites listed in the [development environment guide](https://github.com/eclipse/org.aspectj/blob/master/docs/developer/IDE.md#aspectj-development-tools-ajdt) which were missing are not listed with the corresponding Eclipse IDE versions they are compatible with.

Thanks for kicking my rear end, reminding me of this task. 🙂

**Comment by marioja** [comment]
Glad I could help.  I noticed a few other places which are outright wrong.  It will be my pleasure to kick your rear end once more a few times 😄
