### ISSUE TITLE
Source JARs for AJDE, weaver and runtime are empty

### ISSUE THREAD

**Issue by kriegaex** [eclipse/ajdt#9]
While starting to look into #8, I compared source and binary JARs created by Tycho in AJDT vs. the originals from AspectJ. I noticed that the source JARs are quasi empty, only containing the additional content mentioned in _build.properties_, i.e. only _about.html_ plus OSGi manifest. It is actually pretty easy to fix by adding a section like

```xml
<configuration>
  <additionalFileSets>
    <fileSet>
      <directory>${project.basedir}/source</directory>
      <includes>
        <include>**/*</include>
      </includes>
    </fileSet>
  </additionalFileSets>
</configuration>
```

to the Tycho source plugin configuration for those 3 modules, similar to how it is already done for the binary JARs, e.g. here: https://github.com/eclipse/ajdt/blob/9f7a0fee27b49ae845019ad5f993e47325c14c5d/org.aspectj.ajde/pom.xml#L23-L32

Simply adding _source_ to `src.includes` does not do it, because then the directory name would be included, too, but we want the content of _source_ in the root of the archive. Probably that is why it was done like this for the binaries, too. I can only speculate why we use non-standard Maven directory names there. Maybe it is because we want to avoid the sources from actually being found by the compiler, because they are only meant to be packaged.

**Comment by kriegaex** [comment]
@aclement, the main reason why I am not simply committing this change but have created an issue for it is that I can ask you if by any chance omitting the source files in those 3 source JARs might have been on purpose and they are meant to be just dummies, because somehow Eclipse or the build process needs them. Is that mean to save space, maybe? If it was just an oversight by Martin Lippert in his build patch for [#484192](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484192), then I can fix that. I am going to ask him, too.

**Comment by kriegaex** [comment]
**Update:** I have inspected old update sites, and it seems that both AJDT and AspectJ source JARs have been empty (only containing meta data) for many years, maybe even forever. OTOH, the fact that [org.aspectj.ajde/build-aj-jars.xml](https://github.com/eclipse/ajdt/blob/9f7a0fee27b49ae845019ad5f993e47325c14c5d/org.aspectj.ajde/build-aj-jars.xml) goes to such great lengths, copying and filtering the sources for both AspectJ upstream JARs, storing them in the SCM, is a clear indicator of the intention to actually include them in the source JARs. Therefore, I have decided to proceed with the merge, leaving however this issue open until I have received feedback.

**Comment by martinlippert** [comment]
> @aclement, @martinlippert: The main reason why I am not simply committing this change but have created an issue for it is that I can ask you if by any chance omitting the source files in those 3 source JARs might have been on purpose and they are meant to be just dummies, because somehow Eclipse or the build process needs them. Is that meant to save space, maybe?
> 
> If it was just an oversight by Martin in his build patch for [#484192](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484192), then I can fix that. I just want to be sure that I am not destroying anything.

To be honest, I don't remember the details here. I think my main goal back then was to move to a tycho-based build that produces the same output as what the build did before tycho - without questioning too much about the why. So I can't really answer your question and could only recommend to do what seems to be the best solution here... :-)

**Comment by aclement** [comment]
I don't recall.

**Comment by kriegaex** [comment]
Then I hope that some users are happy that the source JARs are no longer empty now.
